### PR TITLE
Initial work on a CodeIgniter integration

### PR DESCRIPTION
**Pull request by NickStallman**
This is an initial attempt at a CodeIgniter integration.

It uses CI's hooks to start tracing as quickly as possible, and will trace the CI start up process, the controller, views and database queries.

I've left some functions open for use by CLI scripts (part of my intended use case) however CLI disables tracing by default.

Activation instructions are at the top of the file.

### CODE REVIEW

**Comment by labbati** [comment]
Hey @NickStallman , thanks for the contribution! It is great work and we will be able soon to merge it to the main code base.
However, we are currently work on a way to test different versions of web frameworks (Work is in progress) and we would prefer to avoid merging new web frameworks integrations until we are able to properly test them.
We will follow up on this PR as soon as we can provide clear indications for testing.
Thanks!

Note: in the meantime, I also noted that there are a few errors in lint analysis: https://circleci.com/gh/DataDog/dd-trace-php/4719?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by danielzev** [comment]
Hey guys, any timeline on merging this in? the Portfolium team uses CodeIgniter for its PHP framework, and we're starting to test the BETA PHP APM.

For now, to get going (testing), I think we're just going to put this code into our CI app.

**Comment by labbati** [comment]
Hello everybody! Actually we merged the work to write integration tests for Web Frameworks. @NickStallman would you be interested in write some basic integration tests for the work that you have done?
If yes then we can move forward and think of merging this PR soon.

**Comment by NickStallman** [comment]
@labbati yes I can likely write some tests over the next week or so, following the other frameworks tests as a guide.

@jeisberg Did you make the edit to config/hooks.php? Did you enable composer_autoload and enable_hooks in config/config.php?
If enable_hooks is set to false it just won't work and won't output any error.

**Comment by jeisberg** [comment]
@NickStallman - I got it all working; was just a matter of checking the available classes in the correct scope - cruising along now!

**Comment by erickhun** [comment]
For whoever would like to use this, there is some breaking changes on the namespaces. Also not sure if that worth noticing, this integration works for CI3, but not CI2.

**Comment by morrisonlevi** [comment]
An official CodeIgniter was added in 0.32, with a fix for the integration in 0.35. I'm closing this PR in lieu of this.

@NickStallman, @danielzev, @jeisberg, @erickhun: have you tried the official integration yet?

**Comment by NickStallman** [comment]
@morrisonlevi looks good, however I did need to remove the version check for v3.
The last v2 version was released in October 2015 so realistically no one should be using that anymore.

v2 and v3 are largely the same so the integration still works fine.

Out of curiosity, any reason why the version check is using string comparison instead of PHP's built in version_compare()?

**Comment by morrisonlevi** [comment]
We had several customers request v2, so that's what was implemented. I'll make sure we have official v3 support added to our backlog.

> any reason why the version check is using string comparison instead of PHP's built in version_compare()

Not that I remember; it's been a while now and do not remember.

**Comment by NickStallman** [comment]
@morrisonlevi you can treat v2 and v3 as basically entirely compatible for DDTrace. Just not v1 and v4.

**Comment by erickhun** [comment]
@morrisonlevi @NickStallman  Thanks for keeping the Codeigniter v2 integration ❤️. we have a highly modified v2 version, and this comes really handy

**Pull request closed without merging**
