### PR TITLE
Zero pad the tid and exclude it from OTel tracestate

### PR DESCRIPTION
**Pull request by bwoebi**
### Description

As per our specification, otherwise other tracers may complain about a malformed tid.

### Readiness checklist
- [X] (only for Members) Changelog has been added to the release document.
- [x] Tests added for this feature/bug.

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [X] Milestone is set.
- [X] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Comment by bwoebi** [comment]
Parametric tests failing due to: https://github.com/DataDog/system-tests/pull/1864

**Comment by PROFeNoM** [comment]
I'd be more confident in approving this after it was rebased on top of master or master was merged into this branch, which includes the MDB test fix. OTel tests will likely fail since `t.tid` was removed from the tracestate.

**Comment by bwoebi** [comment]
@PROFeNoM yeah, you're right, fixed these :-)

**Review by PROFeNoM — APPROVED** [review]

**Comment by PROFeNoM** [comment]
FYI: It was closed because the System test PR included the word "fixes"...

**Pull request merged**
