### PR TITLE
Add \DDTrace\get_current_context

### PR DESCRIPTION
**Pull request by Anilm3**
### Readiness checklist
- [ ] (only for Members) Changelog has been added to the release document.
- [ ] Tests added for this feature/bug.

### Reviewer checklist
- [x] Appropriate labels assigned.
- [x] Milestone is set.
- [x] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Review by SammyK — COMMENTED** [review]
LGTM! 👍 Nice work @Anilm3.

Before marking approve, one tiny nit on the API (cc @labbati): WDYT of dropping the `get_` prefix: `\DDTrace\current_context()`. That would make it more consistent with existing getter functions. e.g.:

- `\DDTrace\trace_id()`
- `\DDTrace\additional_trace_meta()`
- `\DDTrace\startup_logs()`

No strong opinion either way though. :)

**Comment by labbati** [comment]
> WDYT of dropping the `get_` prefix: `\DDTrace\current_context()`

Sounds good to me! Thank you both!

**Comment by Anilm3** [comment]
@SammyK, thanks, as suggested I've renamed `get_current_context` to `current_context`.

**Review by SammyK — APPROVED** [review]
Thanks @Anilm3! 💯

**Pull request merged**
