### PR TITLE
Automated native_function_invocation fixes

### PR DESCRIPTION
**Pull request by draco2003**
### Description

Reproduce with:
php php-cs-fixer --rules=native_function_invocation fix src --allow-risky=yes
(php-cs-fixer from : https://cs.symfony.com/)

Details:
https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

### Readiness checklist
- [ ] (only for Members) Changelog has been added to the appropriate release draft. Create one if necessary.
- [ ] Tests added for this feature/bug.

### Reviewer checklist
- [x] Appropriate labels assigned.
- [ ] Milestone is set.
- [ ] Changelog has been added to the appropriate release draft. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Comment by draco2003** [comment]
FYI, my fixer run seems to have been overly agreesive. Will submit a new PR with significantly less changes since it should only be add the \ for optimizable functions. 

Also an alternative syntax is the :
`use function is_array;`

Let me know if that is peferrable to the inline \is_array syntax.

**Comment by morrisonlevi** [comment]
I think the PR is fine as it is. I don't like `use function xxx;` up at the top, and I think only doing the optimizable ones doesn't make sense.

Of course, other team members are free to chime in :)

**Comment by morrisonlevi** [comment]
If you were to update to the latest master and re-run the script it could probably be merged right away this time -- we've fixed the image access issue you hit here. Would you be interested in doing that, or should we consider this closed?

**Comment by morrisonlevi** [comment]
Closed since it's pretty far out of date. Sorry that you happened to open it at a time that our builds were broken and we couldn't merge it right away.

For anyone else who reads this: we can't do "use function is_array" because we need to support PHP 5.4 and PHP 5.5 and they don't support that syntax; any future PRs like this would have to use a fully qualified function name.

**Pull request closed without merging**
