### PR TITLE
Add http.route tag to SymfonyIntegration.php

### PR DESCRIPTION
**Pull request by Julian-Louis**
Hello, this is draft pull request adds the http.route tag to the Symfony integration.
Noticing that [PR #2477](https://github.com/DataDog/dd-trace-php/pull/2477) was closed, I decided to take the initiative to implement this feature.

Can you please provide your feedback on this proposal/implementation? If approved, I'll proceed with implementing tests to further validate the changes.

Thank you for your review !

### Reviewer checklist
- [ ] Test coverage seems ok.
- [ ] Appropriate labels assigned.

### CODE REVIEW

**Comment by bwoebi** [comment]
Hey @Julian-Louis,

thanks for taking the initiative here! I think this approach may not be fully correct.

Like, normalization is basically trying to recognize ids, but if you have routes which contain a name, not matching these patterns, the parameter will be assigned wrongly, I think.

E.g. let's assume a route `/posts/{category}/{id}` - we do a request `/posts/cooking/12`.
We'll end up with a normalized form `/posts/cooking/?`.
The parameters being replaced, it will be `/posts/cooking/{category}`, which is not right.

**Comment by Julian-Louis** [comment]
Hello, thank you for your feedback !
I understand your concerns and will explore alternative implementations. I'll update the code as soon as I can

**Comment by Julian-Louis** [comment]
Hello @bwoebi,

I revisited my code and implemented a new approach! By leveraging a reflection class, I gained access to the Symfony container, allowing me to utilize the router matcher. This allows me to accurately retrieve the actual parameters and URL of the route. And I normalized the URL by replacing parameter keys with corresponding values in the URL.

What do you think of it ?

**Comment by bwoebi** [comment]
Hmm @Julian-Louis, I think this code has another missing case:

Now a route `/posts/{category}/{id}` matching `/posts/1/1` will be converted to `/posts/{category}/{category}`, if I read that code correctly?

I've been looking through the Symfony code right now, and am finding Router::getRouteCollection(), which contains all routes with their names and paths. Either the $router->options['cache_dir'] is set and the Router::getRouteCollection() is loaded if uncached or it's not set and it's always present.
So, isn't it simply possible to fill our own cache file with our own name=>paths mapping and use this? (if cache is enabled, otherwise, we'll just walk the routecollection directly?

A direct mapping from a cache file should be quite fast then I suppose?

Note that I have no idea what I'm talking about though, not an expert in Symfony, just navigating through their codebase and trying to figure out what's going on there.

**Comment by Julian-Louis** [comment]
@bwoebi 
I just updated my code and now `/posts/{category}/{id}` (`/posts/1/1`) will be converted to `/posts/{category}/{id}` instead of `/posts/{category}/{category}` anymore, sorry for the mistake.

I'm not a big symfony expert too, but I'll try to take a look on the way you suggest

**Comment by bwoebi** [comment]
I think the current solution is probably _viable_. It's not 100% correct (e.g. `/posts/posts` with a route `/posts/{name}` will be now `/{name}/posts`).
I'm not sure if that's the only edge case, it's maybe edge case enough to be accepted.

I also have no idea of the performance characteristics; I'll leave that to somebody else from my team to evaluate :-)

**Comment by cataphract** [comment]
Superseded by https://github.com/DataDog/dd-trace-php/pull/2992 . I based it on your work. Thank you.

**Pull request closed without merging**
