### PR TITLE
fix: CI exiting with non-zero code on post-install audit fails

### PR DESCRIPTION
**Pull request by PROFeNoM**
### Description

The 8.0 and 8.1 web [tests](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/12528/workflows/837d6420-d1c7-476f-93ee-5247b07162b6/jobs/2813705?invite=true#step-131-64924_51) started failing on the CI a few hours ago. This is due to the [2.6.0](https://github.com/composer/composer/releases/tag/2.6.0) release of composer/composer, which includes [#11362](https://github.com/composer/composer/pull/11362).

~This PR sets the composer version of the failing tests to 2.5.6.~
This pull request modifies the Makefile command for composer update to handle exit code 5.

### Readiness checklist
- [X] (only for Members) Changelog has been added to the release document.
- [X] Tests added for this feature/bug.

### Reviewer checklist
- [X] Appropriate labels assigned.
- [X] Milestone is set.
- [X] Changelog has been added to the release document. For community contributors, the reviewer is in charge of this task.

### CODE REVIEW

**Comment by bwoebi** [comment]
This sounds like a special exit code - can't we just check for that instead of forcing composer to be limited?

**Comment by PROFeNoM** [comment]
Change to handle the exit code 5 specifically

**Comment by PROFeNoM** [comment]
Do not merge yet. This should be fixed in the hotfix composer/composer just made ([2.6.2](https://github.com/composer/composer/releases/tag/2.6.2)). I'm re-running master to see if it still fails :+1:

**Comment by PROFeNoM** [comment]
Fixed with 2.6.2. This PR is no longer relevant :+1: Closing it.

**Pull request closed without merging**
