### PR TITLE
Added DD_TRACE_QUERY_STRING_RESOURCE_PARAMS option

### PR DESCRIPTION
**Pull request by mauriciogior**
### Description
Added `DD_TRACE_QUERY_STRING_RESOURCE_PARAMS` array option to keep selected query string attributes in the uri 
 to resource mapper.

### Readiness checklist
- [ ] (only for Members) Changelog has been added to the release document.
- [x] Tests added for this feature/bug.

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [ ] Milestone is set.
- [ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Comment by labbati** [comment]
Thank you @mauriciogior for contributing this. We commit to review it in the next very few days. The reds in tests are due to a problem with CENTOS 6 EOL that we are addressing in #1116 and that blocks any other merge at the moment. I will ask you to rebase on master once we merge #1116.

**Comment by mauriciogior** [comment]
@labbati Thanks. Do you have a guide on how to generate the final .deb file so I can install it easier on our servers instead of manually copying and pasting the extension?

Thanks.

**Comment by renatofl** [comment]
Hello,

Any news on this ? Do we have any way to enable query strings in resource map?

**Comment by labbati** [comment]
Unfortunately this has not been scheduled yet, as we are focusing on other priorities. We will let you know as soon as we can prioritize it.

**Comment by bwoebi** [comment]
Closing, as this PR is outdated and now superseded by #1566.

**Comment by JanibashaShaikTR** [comment]
@labbati  any update on this feature?

**Comment by bwoebi** [comment]
@JanibashaShaikTR check the description of #1566 - this has been released with 0.74.0.

**Pull request closed without merging**
