### PR TITLE
Add official 7.3 support

### PR DESCRIPTION
**Pull request by pawelchcki**
### Description
This PR adds tests and removes obsoleted integration tests for PHP 7.3
In addition a suppression for Valgrind False positives has been added. Its been identified that its due to handcrafted assembly being used in PHP.  

Everything else "just works"(tm)

### Readiness checklist
- [x] [Changelog entry](docs/changelog.md) added, if necessary
- [x] Tests added for this feature/bug

### CODE REVIEW

**Comment by maxcountryman** [comment]
Any sense of when this will be merged and released?

Currently APM is broken for us.

**Comment by SammyK** [comment]
@maxcountryman We'll be doing another release sometime this week so it shouldn't be too much longer. :)

**Comment by maxcountryman** [comment]
@SammyK is there a way to prioritize this?

Again APM is fully offline for us so this means us and I'm sure other Datadog customers are flying in the blind...

**Comment by SammyK** [comment]
@maxcountryman Absolutely! A release with PHP 7.3 support is our top priority at the moment. As soon as any remaining blockers have been addressed, we'll roll the release and update this thread to to let you know. :)

**Comment by SammyK** [comment]
Hey @maxcountryman! We just [shipped version `0.22.0`](https://github.com/DataDog/dd-trace-php/releases) which includes support for PHP 7.3. Let us know if you have any issues with it! :)

**Pull request merged**
