### PR TITLE
Add PSR18 tracing support in any PSR18 ClientInterface

### PR DESCRIPTION
**Pull request by gmessier**
### Description

The PSR18 (Http client) interface as a generic "sendRequest" method to send HTTP requests. This interface is implemented by many HTTP Clients (like Guzzle for example).

This PR is to add tracing to this "sendRequest" method.

This PR is a variation of this one: https://github.com/DataDog/dd-trace-php/pull/1936
Only one of them should be merged.

NOTE: I didn't add tests as I'm not really sure how to handle them. I hope I didn't miss anything to add a new integration.

### Readiness checklist
- [ ] (only for Members) Changelog has been added to the release document.
- [ ] Tests added for this feature/bug.

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [x] Milestone is set.
- [ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Comment by gmessier** [comment]
I named the integration PSR because I guess in the future we could also add tracing for some other PSRs interfaces.

**Comment by gmessier** [comment]
This PR needs this other one to work correctly: https://github.com/DataDog/dd-trace-php/pull/1914

**Comment by gmessier** [comment]
I don't know if you prefer to name the integration "Psr" or "PSR" (both seems ok for me), but using "PSR" created a bug in the tests (it seems the test check the order of the integrations in an array and the "expected" array incorrectly sort the keys. The keys are retrieved using the directories and for some reasons "PSR" was sort before "Pcntl" (but "Psr" is correctly sorted after "Pcntl".

**Comment by bwoebi** [comment]
This looks already quite good to me. However, I think it should be a `Psr18` integration. Like, Psr has vastly different areas it impacts and a future logging integration (for example, i.e. Psr3) should not be conflated with a http interface.

I'll handle the tests, probably sometime next week then. Thanks for your effort!

**Comment by gmessier** [comment]
I was not sure what was the best choice between one integration for all PSRs or one per PSR. Do you want me to change the name everywhere or you will do it when you will work on tests?

**Comment by bwoebi** [comment]
I wouldn't mind if you changed it :-)

**Review by bwoebi — APPROVED** [review]
Thanks @gmessier for providing the base (which I essentially left unchanged and just added the tests).

Merging :-)

**Pull request merged**
