### PR TITLE
Slightly Improve OTel Performances

### PR DESCRIPTION
**Pull request by PROFeNoM**
### Description

- Don't build an attributes builder instance since we don't apply attributes limit anyway
- Don't build a new tracestate instance if the tracestate didn't change
- More efficient condition checks

### Reviewer checklist
- [ ] Test coverage seems ok.
- [ ] Appropriate labels assigned.

### CODE REVIEW

**Review by bwoebi — APPROVED** [review]
Peeeerformance :-) More! :-)

**Comment by bwoebi** [comment]
Hm, the Otel parametric tests fail.

**Comment by PROFeNoM** [comment]
Will fix it on monday

**Comment by PROFeNoM** [comment]
Made a [PR](https://github.com/DataDog/system-tests/pull/2269) to the system-tests repo to address the parametric test failure

**Pull request merged**
