### PR TITLE
Add gdbinit files for php 8.0 and 8.1

### PR DESCRIPTION
**Pull request by labbati**
### Readiness checklist
- [x] (only for Members) Changelog has been added to the release document.
- ~[ ] Tests added for this feature/bug.~

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [ ] Milestone is set.
- [ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Comment by bwoebi** [comment]
What do you need these for? As in, when isn't it enough to do `source /usr/local/src/php/.gdbinit` in gdb?

**Comment by labbati** [comment]
For cases when you have not PHP's sources, but you mount dd-trace-php, e.g. our `dd-trace-php-solutions` repo, randomized tests and rel-env images.

If we want to remove them it is not a big deal (I can wget them, no problem) but we should either remove them for all versions in that folder or to have them for all versions.

**Review by bwoebi — APPROVED** [review]
Ah we already have existing gdbinit files (never seen those), then it's a no-brainer :-)

**Comment by labbati** [comment]
Thanks

**Pull request merged**
