### PR TITLE
BGS shutdown/flush

### PR DESCRIPTION
**Pull request by krakjoe**
### Description

The background sender is configured with a shutdown timeout, which defines the maximum amount of time the shutdown routine will wait for the writer thread before the routine ignores the request to join.

This is not safe, threads must be joined for predictable behaviour.

In the case where the timeout is reached, the shutdown routine needs to cancel the writer thread and then join with it at the last opportunity.

Failing to fulfil the contract of the function at the last opportunity leads to surprising behaviour, like the background sender trying to read from memory that was freed at mshutdown stage.

### Readiness checklist
- [ ] (only for Members) Changelog has been added to the release document.
- [ ] Tests added for this feature/bug.

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [ ] Milestone is set.
- [ ] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Review by bwoebi — DISMISSED** [review]
This looks safe to me, thanks for the patch Joe :-)

**Review by bwoebi — APPROVED** [review]

**Comment by morrisonlevi** [comment]
In the longer term, there are better ways to share data and clean up. However, this will be a more invasive change, so it's off the table for now.

I didn't know about these functions before. From reading the docs, this bit does have me concerned:

> Calling longjmp(3) (siglongjmp(3)) produces undefined results if
> any call has been made to pthread_cleanup_push() or
> pthread_cleanup_pop() without the matching call of the pair since
> the jump buffer was filled by setjmp(3) (sigsetjmp(3)).

**Comment by bwoebi** [comment]
Though the BGS (nor curl https://github.com/curl/curl/search?q=longjmp is empty) is not using the zend_try nor the *jmp() API directly, so that should be fine.

**Comment by morrisonlevi** [comment]
I won't block the PR -- I just don't know enough about these APIs to do that. If you two think it's better this way for the short-term and that it will handle the recent ASAN failure in CI, then go ahead.

**Pull request merged**
