### PR TITLE
Fix a memory leak when overriding default arguments in install_hook (PHP7.2-)

### PR DESCRIPTION
**Pull request by PROFeNoM**
### Description

While finalizing the logs correlation, I ran into the following [memory leak](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/11517/workflows/148816c9-5aa2-43a2-8c35-129239b397b1/jobs/2432168/tests#failed-test-0). This leak only happens for versions anterior to PHP7.2, as it seems the garbage collector was [changed](https://prototype.php.net/versions/7.3.0/) with the [7.3](https://github.com/php/php-src/pull/3165/files) version.

I couldn't find why this only happens for arrays (yet?), there is certainly a better fix. My instinct tells me that there must be something going on with the refcount...

### Readiness checklist
- [X] (only for Members) Changelog has been added to the release document.
- [X] Tests added for this feature/bug.

### Reviewer checklist
- [X] Appropriate labels assigned.
- [X] Milestone is set.
- [X] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Comment by PROFeNoM** [comment]
Marked this as a draft while I find a better fix. Working on it.

**Comment by PROFeNoM** [comment]
_Notes to myself_ 

It seems like the refcount of `arg` gets increase in php7.3+ when using `ZVAL_COPY(arg, val)` whereas it doesn't in php7.2-

**php 8.2**
```
685	            ZVAL_COPY(arg, val);
1: *arg->value->counted = {gc = {refcount = 1, u = {type_info = 86}}}
2: *val->value->counted = {gc = {refcount = 1, u = {type_info = 7}}}
(gdb) 
693	        ++arg;
1: *arg->value->counted = {gc = {refcount = 2, u = {type_info = 7}}}
2: *val->value->counted = {gc = {refcount = 2, u = {type_info = 7}}}
```

**php7.2**
```
685	            ZVAL_COPY(arg, val);
1: *arg->value->counted = {gc = {refcount = 2, u = {v = {type = 7 '\a', flags = 128 '\200', gc_info = 0}, type_info = 32775}}}
2: *val->value->counted = {gc = {refcount = 1, u = {v = {type = 7 '\a', flags = 128 '\200', gc_info = 0}, type_info = 32775}}}
(gdb) 
693	        ++arg;
1: *arg->value->counted = {gc = {refcount = 2, u = {v = {type = 7 '\a', flags = 128 '\200', gc_info = 0}, type_info = 32775}}}
2: *val->value->counted = {gc = {refcount = 2, u = {v = {type = 7 '\a', flags = 128 '\200', gc_info = 0}, type_info = 32775}}}
```

**Comment by PROFeNoM** [comment]
Changed the 'fix' so that If arg already holds a value, the refcount is decremented (CI fails atm because the tarpc package was renamed to forked-tarpc on the branch, but you already know that)

**Review by bwoebi — APPROVED** [review]
Thanks, this looks right now :-)

**Pull request merged**
