### PR TITLE
Fix error reporting in case of fatal errors

### PR DESCRIPTION
**Pull request by labbati**
### Description

This PR improves error reporting marking a trace as error (and reporting a 500) in cases when a framework does not handle errors are such and in case of but `E_ERROR` and `E_USER_ERROR` fatal errors.

_Notes_
Reported stack traces are not changed in case of frameworks that handle exceptions, e.g. Symfony and Laravel. While in case of frameworks not handling exception on their own, we try to fill in the proper metadata based on the info we can obtain from `error_get_last()`

### Readiness checklist
- [x] (only for Members) Changelog has been added to the appropriate release draft. Create one if necessary.
- [x] Tests added for this feature/bug.

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [ ] Milestone is set.
- [ ] Changelog has been added to the appropriate release draft. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Comment by laurenty** [comment]
FYI, this PR was listed as a fix on the 0.35.0 release.

**Comment by labbati** [comment]
Good catch @laurenty, sorry about the confusion here. I updated the release marking that line as an error. We still have some work to do for this as we weren't able to so far to clearly and properly detect/set the status code.

**Comment by laurenty** [comment]
Hi @labbati Any idea how much work is left to complete this PR?

**Comment by labbati** [comment]
We are having a hard time covering all the edge-cases without being too obtrusive. We are still evaluating what is the best path moving forward. Unfortunately, I had to temporarily pause the work on this. Let me try to prioritize it again and get back to you with a more precise ETA.

**Comment by laurenty** [comment]
Hi @labbati, any update on this issue? Thanks

**Comment by labbati** [comment]
A quick update on this PR. The work for this fix was blocked by a big refactor to our API. With the release of version 0.48.0 we will have all the supported PHP versions sandboxed (i.e. errors in our instrumentations will not cause apps to crash) and we can move on fixing this long-standing issue.

The blocking tasks are:
 - https://github.com/DataDog/dd-trace-php/pull/970
 - https://github.com/DataDog/dd-trace-php/pull/960
 - Sandboxing PHP 5.4 (in progress)

Once we merge and release the above features we plan to start working on this. At that point we will provide an ETA for the release.

**Comment by morrisonlevi** [comment]
Closing in favor of PR #767. Currently planning for this to go out in version 0.49.0.

**Pull request closed without merging**
