### PR TITLE
Add Nette integration

### LINKED ISSUE #489: Nette framework integration
Hi,

we are using Nette framework for our projects and it would be nice to have integration. I can prepare PR here. But the question is, are you going to support frameworks like Nette in this repository?

Thanks!

Nette framework: https://github.com/nette/nette

### PR DESCRIPTION
**Pull request by kozaktomas**
Supported Nette framework versions:
- 2.4 (PHP 5.6+)
- 3.0 (PHP 7.1+)

Both versions are tested.

Integration is loaded after `Nette\Configurator::__construct`. It's one of the first object created in Nette.

## Spans:
- createContainer - dependency injection container creation
- createRobotLoader - Nette framework autoloader
- Application:run
- Presenter:run - controller
- Presenter:onError - error detection
- Route:match - HTTP request router
- createTemplate, render, renderToString Latte tempate engine - template name included

Closes #489

### Readiness checklist
- [x] [Changelog entry](docs/changelog.md) added, if necessary
- [x] Tests added for this feature/bug

### CODE REVIEW

**Comment by pawelchcki** [comment]
Wow! Thanks for this awesome contribution @kozaktomas! 
We'll take a closer look at it as soon as possible (although from the firce glance it looks very complete !!)

**Comment by kozaktomas** [comment]
Hi @pawelchcki 

I rebased my branch few times. It would be really nice to have it in the next version of this package. 🙏

**Comment by SammyK** [comment]
Thank you so much for this awesome PR @kozaktomas! My apologies for the delay for a code review. I'll make sure to get this reviewed this week. :)

**Comment by SammyK** [comment]
@kozaktomas We've got this slated for not the nest release, but the release after that. That will give us some time to add the new Sandbox API to your awesome integration and then we can get it released. :)

**Comment by kozaktomas** [comment]
Hi @SammyK. I did deeper testing (with agent) and I found a bug. I've added one additional commit. I also did rebase with master. Sorry for inconvenience. :)

**Comment by roman-vohnik** [comment]
Hi there!

I am trying DataDog APM with app based on Nette Framework right now and found this PR, why is it closed and not merged? It seems to me like it has already been almost done.

**Comment by SammyK** [comment]
This was completely my fault for missing this for release so long ago. I'm sorry about that @kozaktomas.

@roman-vohnik This PR uses the legacy API for the integration which no longer ships with the tracer, but we should still be able to use the fantastic work @kozaktomas has already done and update it to use the sandbox API. Unfortunately we're not able to provide an ETA on when we will be able to refactor this at the moment, but I have added this to our internal project tracking and it is on our radar.

**Comment by SammyK** [comment]
This PR for the Nette framework integration (#489) has been revived and merged via #1220 and will be included in the next release. Thank you again @kozaktomas for the original work on this and thank you @Anilm3 for reviving this PR. My apologies again for letting this PR slip through the cracks.

**Pull request closed without merging**
