### PR TITLE
Add IPv6 support to DD_AGENT_HOST

### LINKED ISSUE #1667: [BUG] agent_url issue with ipv6 only Kubernetes
### Bug description
It appears when using DDTrace in a IPv6 only environment, the agent url may be detected as invalid.
Amazon AWS EKS now supports IPv6 only clusters

### PHP version
7.4.30

### Tracer version
0.73.0

### Diagnostics and configuration

The DD_AGENT_HOST variable is set correctly to a IPv6 address of the DD Agent.
```
DD_AGENT_HOST=2a05:d01c:806:8003:xxxx:xxxx:d572:58be
```

This gets converted to the agent_url:
```
agent_url: http://2a05:d01c:806:8003:xxxx:xxxx:d572:58be:8126"
```

Which results in the agent_error:
```
URL using bad\/illegal format or missing URL
```

It should probably construct the url like this instead:
```
agent_url: http://[2a05:d01c:806:8003:xxxx:xxxx:d572:58be]:8126"
```

#### Output of phpinfo() (ddtrace >= 0.47.0)
```
DATADOG TRACER CONFIGURATION => {"date":"2022-07-25T02:20:37Z","os_name":"Linux lp-accounts-694f758f9c-dlcst 5.4.196-108.356.amzn2.x86_64 #1 SMP Thu May 26 12:49:47 UTC 2022 x86_64","os_version":"5.4.196-108.356.amzn2.x86_64","version":"0.73.0","lang":"php","lang_version":"7.4.21","env":"produk","enabled":true,"service":"lp-accounts","enabled_cli":false,"agent_url":"http:\/\/2a05:d01c:806:8003:xxxx:xxxx:d572:58be:8126","debug":false,"analytics_enabled":false,"sample_rate":1,"sampling_rules":[],"tags":[],"service_mapping":[],"distributed_tracing_enabled":true,"priority_sampling_enabled":true,"dd_version":"b6ec9edb","architecture":"x86_64","sapi":"cli","datadog.trace.request_init_hook":"\/opt\/datadog-php\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php","open_basedir_configured":false,"uri_fragment_regex":null,"uri_mapping_incoming":null,"uri_mapping_outgoing":null,"auto_flush_enabled":false,"generate_root_span":true,"http_client_split_by_domain":true,"measure_compile_time":true,"report_hostname_on_root_span":false,"traced_internal_functions":null,"auto_prepend_file_configured":false,"integrations_disabled":"default","enabled_from_env":false,"opcache.file_cache":null,"agent_error":"URL using bad\/illegal format or missing URL"}
```

### PR DESCRIPTION
**Pull request by bwoebi**
### Description

Fixes #1667.

### Readiness checklist
- [x] (only for Members) Changelog has been added to the release document.
- [x] Tests added for this feature/bug.

### Reviewer checklist
- [ ] Appropriate labels assigned.
- [x] Milestone is set.
- [x] Changelog has been added to the release document. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Comment by NickStallman** [comment]
I just noticed I wasn't getting APM logs, and I found this in the phpinfo() logs:

```
{
  "date": "2022-11-08T01:55:34Z",
  "os_name": "Linux app-7fc989d984-6pddh 5.4.196-108.356.amzn2.x86_64 #1 SMP Thu May 26 12:49:47 UTC 2022 x86_64",
  "os_version": "5.4.196-108.356.amzn2.x86_64",
  "version": "0.81.1",
  "lang": "php",
  "lang_version": "7.4.30",
  "env": "produk",
  "enabled": true,
  "service": "app",
  "enabled_cli": false,
  "agent_url": "http://2a05:d01c:0000:0000:0000:0000:44d5:56b0:8126",
  "debug": false,
  "analytics_enabled": false,
  "sample_rate": 1,
  "sampling_rules": [],
  "tags": [],
  "service_mapping": [],
  "distributed_tracing_enabled": true,
  "priority_sampling_enabled": true,
  "dd_version": "27c7ce36",
  "architecture": "x86_64",
  "sapi": "apache2handler",
  "datadog.trace.request_init_hook": "/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php",
  "open_basedir_configured": false,
  "uri_fragment_regex": null,
  "uri_mapping_incoming": null,
  "uri_mapping_outgoing": null,
  "auto_flush_enabled": false,
  "generate_root_span": true,
  "http_client_split_by_domain": true,
  "measure_compile_time": true,
  "report_hostname_on_root_span": false,
  "traced_internal_functions": null,
  "auto_prepend_file_configured": false,
  "integrations_disabled": "default",
  "enabled_from_env": true,
  "opcache.file_cache": null,
  "agent_error": "URL using bad/illegal format or missing URL"
}
```
datadog.agent_host is set to 2a05:d01c:0000:0000:0000:0000:44d5:56b0	

So the URL isn't being formatted correctly, even after this patch? I verified with the latest 0.81.1 as well.

**Comment by bwoebi** [comment]
@NickStallman Note that this patch wasn't merged. We still want to, but we need to update the profiler too (using the same configs). I haven't gotten to it yet.

**Comment by NickStallman** [comment]
Ahh I just noticed that. It'll be good once it's merged as right now I can't (very easily) use APM on a new Kubernetes cluster. Thanks

**Review by realFlowControl — APPROVED** [review]
I added some tests for the `detect_uri_from_config()` function in the profiler.
LGTM 🚀

**Pull request merged**
