### PR TITLE
Update spdlog so it works with recent musls

### PR DESCRIPTION
**Pull request by cataphract**
https://github.com/gabime/spdlog/commit/287a00d364990edbb621fe5e392aeb550135fb96

### Reviewer checklist
- [ ] Test coverage seems ok.
- [ ] Appropriate labels assigned.

### CODE REVIEW

**Comment by bwoebi** [comment]
That probably fixed that particular issue, but now a load of new errors appear, probably due to the other changes between these commits...

**Comment by cataphract** [comment]
Rebase and fixed the errors related to the new spdlog, at least in the main helper binary.

**Review by bwoebi — APPROVED** [review]
Looks good, thanks Gustavo.

**Review by Anilm3 — APPROVED** [review]
lgtm

**Comment by Anilm3** [comment]
The integration tests are failing because they're expecting an image for PHP 8.4 which doesn't exist at the moment, you can disable the 8.4 test for now and I'll add this to the backlog.

**Pull request merged**
