### PR TITLE
Add official support for PHP 7.4

### PR DESCRIPTION
**Pull request by SammyK**
### Description

This PR adds official support for PHP 7.4.

Related to #670.

### Readiness checklist
- [x] (only for Members) Changelog has been added to the appropriate release draft. Create one if necessary.
- [x] Tests added for this feature/bug.

### Reviewer checklist
- [x] Appropriate labels assigned.
- [x] Milestone is set.
- [ ] Changelog has been added to the appropriate release draft. For community contributors the reviewer is in charge of this task.

### CODE REVIEW

**Comment by nesl247** [comment]
Out of curiosity, why does simply adding 7.4 into the test suite take weeks to do?

**Comment by SammyK** [comment]
@nesl247 That’s a fair question. Most of this work has gone into orchestrating multiple PHP 7.4 containers across multiple repos and this PR is the final glue that puts it all together. We’re starting to consolidate the container orchestration such that it can be done in one place which should make these kind of changes go much faster in the future. :)

**Comment by nesl247** [comment]
Thanks for the answer @SammyK.

**Comment by Majkl578** [comment]
> That’s a fair question. Most of this work has gone into orchestrating multiple PHP 7.4 containers across multiple repos and this PR is the final glue that puts it all together. We’re starting to consolidate the container orchestration such that it can be done in one place which should make these kind of changes go much faster in the future. :)

Sorry but I don't think this is a good excuse for blocking compatibility with latest stable PHP version. Stable PHP 7.4.0 was released 7 weeks ago, 7.4.0RC1 over 3 months ago. Next week there will be PHP 7.4.2 and Datadog extension has still no compatible release even after assurances it'll be ready on January 15th. :confused: 

For comparison, New Relic had their extension compatible with PHP 7.4.0 on December 5th, one week after PHP 7.4.0 release.

**Comment by priyanshi-gupta** [comment]
Your point is absolutely valid, and the feedback is highly appreciated.

To ensure there is no lag in future and be more prepared for PHP.next version releases, we are extensively re-evaluating our release strategy, and will be running tests against the nightly builds of PHP in our CI.

You can download the nightly build with PHP 7.4 support to start getting your containers and staging environments ready before the official release next week here: https://106602-119990860-gh.circle-artifacts.com/0/all/packages.tar.gz

For more questions about SLA of releases, and any concern, do not hesitate to reach out here or on help@datadog.com (You can mention me to route it directly).

**Pull request merged**
