### PR TITLE
Add release notes for 0.92.1

### PR DESCRIPTION
**Pull request by bwoebi**
A small hotfix with a couple fixes.

### CODE REVIEW

**Comment by Anilm3** [comment]
I might add a small change to appsec on Monday morning. I'll update this PR once the patch is released in the appsec repository.

**Review by morrisonlevi — APPROVED** [review]
LGTM, thanks!

**Comment by bwoebi** [comment]
Okay @Anilm3 - just do a PR to master and we'll push it here afterwards then. (or are you just re-releasing 0.14.1 on appsec? That's fine too)

**Comment by Anilm3** [comment]
> Okay @Anilm3 - just do a PR to master and we'll push it here afterwards then. (or are you just re-releasing 0.14.1 on appsec? That's fine too)

Actually, I might not make it, so please proceed without me and I'll release another patch later on.

**Pull request merged**
